-- Database Rebuild

-- Create the Type ENUM
CREATE TYPE public.acc_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.acc_type
    OWNER TO cse340;

-- Create Classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMERY KEY (classification_id)
);

-- Create Inventory table
CREATE TABLE IF NOT EXISTS public.inventory 
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
);

-- Create relation between Inventory and Classification
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification
    FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 4. REPLACE function to update
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior') 
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 5. inner join to combine data from two tables
SELECT
	inv_make, inv_model
FROM inventory
INNER JOIN classification
ON inventory.classification_id = classification.classification_id
WHERE classification.classification_name = 'Sport';

-- 6 update the path of image anf the thumbnail
UPDATE inventory
SET 
  inv_image = REPLACE(inv_image, 'images/', 'images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, 'images/', 'images/vehicles/');